name: Deploy Spring Boot Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Save Docker image as tar
        run: docker save -o myapp.tar myapp:latest

      - name: Verify Docker tar file
        run: |
          if [ ! -f myapp.tar ]; then
            echo "ERROR: myapp.tar does not exist!"
            exit 1
          fi
          ls -lh myapp.tar

      - name: Fix permissions for SCP
        run: chmod 644 myapp.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "myapp.tar"
          target: "/home/ubuntu/myapp/"
          strip_components: 0

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            mkdir -p /home/ubuntu/myapp
            cd /home/ubuntu/myapp

            if [ ! -f myapp.tar ]; then
              echo "ERROR: myapp.tar not found on EC2!"
              exit 1
            fi

            docker load -i myapp.tar

            if [ $(docker ps -aq -f name=myapp) ]; then
              docker stop myapp || true
              docker rm myapp || true
            fi

            docker run -d --name myapp -p 8080:8080 myapp:latest

            docker ps -a | grep myapp
